### ISSUE TITLE
CI: random fail returns valid API and gateway addresses

### ISSUE THREAD

**Issue by thisconnect** [ipfs/js-ipfsd-ctl#158]
Ci failes "sometimes" on Node 4 sometimes on Node 6

See the 2 builds from another PR (https://github.com/ipfs/js-ipfsd-ctl/pull/153 should be unrelated to the test)
fails on Node 6 https://travis-ci.org/ipfs/js-ipfsd-ctl/builds/244451297
fails on Node 4 https://travis-ci.org/ipfs/js-ipfsd-ctl/builds/245233174

each time same test
```
  1 failing
  1) daemons startDaemon starts the daemon and returns valid API and gateway addresses:
     Uncaught AssertionError: expected null to be an instance of Multiaddr
      at async.waterfall (test/index.spec.js:450:52)
      at node_modules/async/dist/async.js:421:16
      at next (node_modules/async/dist/async.js:5278:29)
      at node_modules/async/dist/async.js:906:16
      at node.startDaemon (test/index.spec.js:443:54)
      at f (node_modules/once/once.js:25:25)
      at Socket.data (src/node.js:236:13)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at Pipe.onread (net.js:547:20)
```

**Comment by diasdavid** [comment]
@thisconnect fixed on https://github.com/ipfs/js-ipfsd-ctl/pull/160/files#r135794850
