### ISSUE TITLE
ipfsd.api.name.publish fails with opaque error message.

### ISSUE THREAD

**Issue by 10thfloor** [ipfs/js-ipfsd-ctl#201]
OS: Sierra, 7.3.0 Darwin Kernel Version 17.3.0 X_86_64

The following code fails:
```

// ... daemon.spawn(ipfsd => ...

ipfsd.api.util.addFromFs(dist, { recursive: true }).then(filesAdded => {
       // Files add works. 
       !err && console.log('Files were added...')
      
      // Hash of directory to publish is valid
      const rootDirHash = filesAdded.pop().hash

      // Publishing fails :(
      ipfsd.api.name.publish(rootDirHash).then((err, result) => {
          !err && console.log(result)
      }).catch(err => {
          console.log(err)    
      })
})
```

With this error:
```
{ Error: Sorry, something went wrong, please retrace your steps.
    at parseError (/Users/MK/vue-ipfs/node_modules/ipfs-api/src/utils/send-request.js:16:17)
    at ClientRequest.res (/Users/MK/vue-ipfs/node_modules/ipfs-api/src/utils/send-request.js:40:14)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at Socket.socketOnData (_http_client.js:439:20)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7) code: 1 }
```
I'm trying to poke into the source, but not having any luck.
✌️

**Comment by VictorBjelkholm** [comment]
Do you see any other errors? According to https://github.com/ipfs/js-ipfs/blob/9f2006e950a198d6c7b0714551eaa8a43652e614/src/http/error-handler.js#L35, it should also print out the error.

Are you using a js-ipfs daemon or go-ipfs daemon with `daemon.spawn`? IPNS is not implemented in the JavaScript implementation, so might be what's gone wrong.

**Comment by 10thfloor** [comment]
Ah. I'm using the js-ipfs daemon. I'll attempt using go-ipfs and respond on this thread. Thanks!

**Comment by diasdavid** [comment]
@10thfloor all good now?

**Comment by 10thfloor** [comment]
Yes. I had to install `go-ipfs-dep` and `go-ipfs` as prohject dependencies, and initialize the Daemonfactory with the 'go' option. Here is what I was building. Works like a charm : )

```js
const path = require('path')
const DaemonFactory = require('ipfsd-ctl')
const ipfsDaemon = DaemonFactory.create({ type: 'go' })

console.log('\nStarting local IPFS node...\n')
ipfsDaemon.spawn(
  {
    // Set disposable to false to publish to your
    // IPFS repo public key
    disposable: false
  },
  function(err, ipfsd) {
    if (err) {
      throw err
    }
    ipfsd.start(() => {
      const dist = path.resolve('./', 'dist')
      ipfsd.api.util.addFromFs(dist, { recursive: true }).then(filesAdded => {
        console.log(filesAdded)
        console.log('\nFiles were added... Publishing...\n')
        ipfsd.api.name.publish(filesAdded.pop().hash).then(result => {
          console.log('Site was published!')
          console.log(`\nVisit: https://gateway.ipfs.io/ipns/${result.name}\n`)
          ipfsd.stop()
        })
      })
    })
  }
)
```

**Comment by diasdavid** [comment]
Awesome! Anything always refer to the README -- https://github.com/ipfs/js-ipfsd-ctl/#batteries-not-included-bring-your-own-ipfs-executable -- and if it is not in the README, let us know or PR so that it gets there :)
