### ISSUE TITLE
Spawn multiple nodes in parallel causes error

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfsd-ctl#253]
```
     Error: Uncaught AssertionError: expected [Error: Unexpected end of JSON inputError: Unexpected end of JSON input
    at request.post.send.end (webpack:///node_modules/ipfsd-ctl/src/factory-client.js:92:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:148359:27)
    at Request.callback (webpack:///node_modules/superagent/lib/client.js:611:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:83804:3)
    at Request.<anonymous> (webpack:///node_modules/superagent/lib/client.js:436:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:83629:12)
    at Request.Emitter.emit (webpack:///node_modules/component-emitter/index.js:133:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:148517:20)
    at XMLHttpRequest.xhr.onreadystatechange (webpack:///node_modules/superagent/lib/client.js:705:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:83898:10)] to not exist (webpack:///node_modules/chai/lib/chai/assertion.js:141:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:87337)
```

The [spawn utility](https://github.com/ipfs/interface-ipfs-core/blob/master/js/src/utils/spawn.js) currently spawns in parallel and fails when spawning 5 nodes for the DHT tests.

This seems to occur only on Linux and only from the webworker tests.

**Comment by diasdavid** [comment]
Solved with https://github.com/ipfs/interface-ipfs-core/pull/276
