### ISSUE TITLE
Simple example in README.md doesn't work

### ISSUE THREAD

**Issue by randomshinichi** [ipfs/js-ipfsd-ctl#49]
When trying to run the disposable daemon example in the README.md, I get this:

```
shinichi@valentine ~/source/test $ node index.js
{ ID: 'QmYTcwsNtCbCBGUTSa671oCrD8XXnVfhGjyHzBhzncdDLs',
  PublicKey: 'CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCxZtTfFEBEfVKPJoWnwZVU/vkjmjDq+5njoC69lX1+xHq+xB/uaX/M/NzYwywFRhwwSIFhYfOswGxcZzsmqt+ZZ+2WJZfjClTNR3VG+vvYhO2EdWvenszecizVtPVnRZ6uT4poECaZIAEHYLvCnMZ6f4D73qn2DHHtSv0upKxClupirIlm633sm+Okly05NW8KtsVpqQT1MSBVZHHRg17tp2eI1B45FxSQYQwTPUFd/j52LX6RSxJkPx11dAeDGjzEOHjzPtxvuUrynabiLW+AONx6jJf7cKWFv8GoFAhFiCm5gb4N/AND6O82svHS8fzGchj4aSWSi38Cb4jm8sU1AgMBAAE=',
  Addresses: 
   [ '/ip4/127.0.0.1/tcp/33400/ipfs/QmYTcwsNtCbCBGUTSa671oCrD8XXnVfhGjyHzBhzncdDLs',
     '/ip4/192.168.1.109/tcp/33400/ipfs/QmYTcwsNtCbCBGUTSa671oCrD8XXnVfhGjyHzBhzncdDLs',
     '/ip4/192.168.20.1/tcp/33400/ipfs/QmYTcwsNtCbCBGUTSa671oCrD8XXnVfhGjyHzBhzncdDLs',
     '/ip4/192.168.238.1/tcp/33400/ipfs/QmYTcwsNtCbCBGUTSa671oCrD8XXnVfhGjyHzBhzncdDLs',
     '/ip4/92.206.50.145/tcp/44173/ipfs/QmYTcwsNtCbCBGUTSa671oCrD8XXnVfhGjyHzBhzncdDLs' ],
  AgentVersion: 'go-ipfs/0.3.11',
  ProtocolVersion: 'ipfs/0.1.0' }
node.js:791
        throw new TypeError('invalid pid');
        ^

TypeError: invalid pid
    at process.kill (node.js:791:15)
    at /home/shinichi/source/test/index.js:7:13
    at finish (/home/shinichi/source/test/node_modules/wreck/lib/index.js:319:16)
    at wrapped (/home/shinichi/source/test/node_modules/wreck/node_modules/hoek/lib/index.js:867:20)
    at onReaderFinish (/home/shinichi/source/test/node_modules/wreck/lib/index.js:365:16)
    at g (events.js:273:16)
    at emitNone (events.js:85:20)
    at emit (events.js:179:7)
    at finishMaybe (_stream_writable.js:468:14)
    at endWritable (_stream_writable.js:478:3
```

**Comment by elsehow** [comment]
Same error here

**Comment by diasdavid** [comment]
Hey @randomshinichi @elsehow , sorry for the trouble, this module has been update, the example and now we have documentation https://ipfs.github.io/js-ipfsd-ctl/, you shouldn't encounter any more problems with that. 

Closing this issue, let me know if you find any obstacle again. Thank you!
